CREATE TABLE IF NOT EXISTS products (
    product_id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DOUBLE PRECISION
);

-- Insert sample data
INSERT INTO products (product_id, name, description, price) VALUES
(26, 'American Beautyberry (Callicarpa americana)', 'Delicate clusters of tiny, light pink to lavender flowers adorn the American Beautyberrys branches. Blooming primarily in late spring and early summer, these inconspicuous flowers give way to the plants signature feature: vibrant, iridescent purple berries. These berries are densely packed around the stems in tight clusters, creating a striking display from late summer through fall and even into winter. The overall form of the plant is a loosely branched shrub, typically growing to a height of 3-8 feet.
', 3.179375691245027),
(50, 'Aster (Aster x frikartii Monch)', 'Aster x frikartii Monch is a stunning aster boasting semi-double, lavender-blue flowers with bright yellow centers. Its daisy-like blooms are profuse and long-lasting, creating a vibrant display. This aster exhibits an upright, bushy habit and typically flowers from late summer into autumn, providing color well into the season.
', 4.595705049215652),
(55, 'Astilbe Peach Blossom', 'Astilbe Peach Blossom is a charming variety with delicate, feathery plumes of soft, peach-pink flowers. Its blooms rise above mounds of fern-like, dark green foliage in early to mid-summer. The flower plumes are densely packed with tiny blossoms, creating a light and airy texture. This Astilbe adds a touch of romantic color and fine texture to shady gardens.
', 9.2845234239187),
(62, 'Babys Breath (Gypsophila elegans Covent Garden)', 'Delicate and airy, Gypsophila elegans Covent Garden, commonly known as Babys Breath, is prized for its cloud-like masses of tiny, pure white flowers. Each individual bloom is small and star-shaped, creating a light and delicate texture. This variety boasts an abundant flowering period, typically blooming from late spring to mid-summer. The plant features slender, branching stems, providing a graceful and sprawling form, perfect for filling gaps in borders or adding a whimsical touch to floral arrangements.
', 2.2170331145896203),
(63, 'Babys Breath (Gypsophila elegans Kermesina)', 'Delicate and airy, Gypsophila elegans Kermesina presents a cloud of tiny, vibrant blooms. Unlike the typical white Babys Breath, Kermesina showcases a lovely shade of rosy-pink to carmine, adding a touch of romantic color to any arrangement. Each small, single flower, measuring about ¼ inch across, features five delicate petals. This cultivar blooms profusely from late spring to mid-summer, creating a wispy, branching form that reaches 12-18 inches in height. Its graceful presence makes it ideal for adding a soft, textural element to bouquets and garden beds.
', 1.741039090435689),
(64, 'Babys Breaths (Gypsophila elegans)', 'Delicate and airy, Babys Breath (Gypsophila elegans) presents a cloud of tiny, star-shaped flowers. Typically pure white, some varieties display a soft blush of pink. Each bloom is small, about 1/4 inch across, and borne in profusion on slender, branching stems. Flowering occurs primarily in summer, from June to August, creating a frothy, ethereal display.
', 6.261228056885014),
(65, 'Baptisias (Baptisia)', 'Striking Baptisia, also known as False Indigo, presents pea-like flowers in upright racemes, typically ranging in colors from deep indigo blue, purple, and vibrant yellow to creamy white and even bi-colored varieties. The blooms are reminiscent of sweet pea blossoms and are followed by attractive, inflated seedpods that add ornamental interest. Flowering occurs primarily in the spring and early summer, typically lasting for several weeks. The plant boasts an upright, bushy form with clover-like trifoliate leaves, providing a handsome foliage display throughout the growing season.
', 9.917985764956816),
(74, 'Bee Balm (Monarda Purple Rooster)', 'Purple Rooster Bee Balm boasts vibrant, raspberry-purple, shaggy flower heads that sit atop sturdy, upright stems. Blooming profusely from mid-summer to early fall, the blossoms are a magnet for hummingbirds, butterflies, and bees. The plant has aromatic, dark green foliage that is resistant to powdery mildew. It typically grows to a height of 2-3 feet and spreads 1-2 feet wide, forming a dense clump.
', 3.089638732443337),
(105, 'Black-eyed Susan (Rudbeckia hirta Cappuccino)', 'Cappuccino Black-Eyed Susan is a captivating variation of the classic wildflower. Its petals, ranging in color from rich mahogany and chocolate brown to warm bronze and burnt orange, create a stunning, layered effect. These petals surround a prominent, dark-brown to almost black central cone. The daisy-like flowers are typically 3-5 inches across and held on strong, upright stems. Blooming profusely from summer through fall, Cappuccino adds a touch of drama and sophistication to any garden.
', 5.288064844902213),
(110, 'Blanket Flower (Gaillardia pulchella)', 'The Blanket Flower (Gaillardia pulchella) is a vibrant wildflower, typically displaying daisy-like flowers with a prominent central disc. Petals, often notched or toothed, radiate outwards in striking shades of red, orange, and yellow, frequently with a banded or concentric pattern reminiscent of a woven blanket. Its form is generally upright and bushy, reaching heights of 1-2 feet. Flowering occurs from early summer through fall, providing a long season of cheerful color.
', 0.20302593130596383),
(116, 'Bleeding Hearts (Lamprocapnos)', 'Bleeding Hearts (Lamprocapnos spectabilis) are charming, heart-shaped flowers, typically a vibrant pink with a white tip that resembles a droplet. These distinctive blossoms dangle gracefully from arching, fleshy stems lined with delicate, fern-like foliage. They bloom in the spring, typically from April to June, adding a touch of whimsical beauty to shady gardens.
', 6.913992974171456),
(118, 'Blue Sage (Salvia azurea)', 'Azure Blue Sage (Salvia azurea) showcases slender spires densely packed with vibrant, sky-blue to azure-colored flowers. These individual flowers are tubular with a distinct two-lipped shape. Blooming typically occurs from late summer into fall, offering a late-season burst of color. The plant itself is upright and somewhat sprawling, with narrow, lance-shaped, grayish-green leaves.
', 9.213701017307534),
(121, 'Bolivian Hummingbird Sage (Salvia oxyphora)', 'Bolivian Hummingbird Sage (Salvia oxyphora) is a showy salvia boasting vibrant, tubular flowers in a striking magenta-pink hue. The blooms are generously produced in whorls along tall, upright flower spikes, rising above a base of large, textured green leaves. Its a long-blooming perennial, typically flowering from late spring through fall, providing a continuous nectar source for hummingbirds and other pollinators. The overall form is upright and bushy, adding height and vertical interest to the garden.
', 9.08053631258393),
(125, 'Bright Green Dudleya (Dudleya virens)', 'Bright Green Dudleya, a succulent perennial, presents a striking rosette of fleshy, lime-green leaves, often tinged with a powdery white coating. The foliage is smooth and elongated, tapering to a point. During its flowering period, typically in late spring to early summer, it sends up an erect flower stalk, or inflorescence, that can reach several inches in height. This stalk bears clusters of creamy-white to pale yellow, star-shaped flowers, adding a delicate contrast to the vibrant green foliage.
', 3.315829851089768),
(134, 'Butterfly Bush (Buddleja davidii Nanho Blue)', 'Nanho Blue Butterfly Bush: A compact variety, Nanho Blue showcases dense, upright panicles of fragrant, rich lavender-blue flowers. Blooming profusely from mid-summer through fall, its narrow, silvery-green foliage provides a lovely contrast to the vibrant blooms. The flower spikes gracefully arch, attracting butterflies and hummingbirds in droves.
', 0.802160465185788),
(150, 'Caladium bicolor Fiesta', 'Caladium Fiesta is a vibrant, fancy-leaved caladium with a dazzling display of color. Its heart-shaped leaves are predominantly bright rosy-pink to red, splashed and mottled with patches of deep green and white. The strong contrast between colors creates a festive, eye-catching appearance. While caladiums do flower, their blooms are insignificant and typically removed to encourage larger, more colorful foliage. The foliage emerges in spring and lasts throughout the warm summer months, providing a long season of tropical beauty.
', 3.0548143748285166),
(156, 'Canna CannaSol™ Lily', 'The Canna CannaSol™ Lily is a vibrant explosion of sunshine yellow and fiery orange. Its large, showy blooms feature broad, slightly ruffled petals that create a bold, tropical appearance. Blooming from mid-summer through fall, the CannaSol™ Lily provides a long-lasting display. Its upright, sturdy stalks are adorned with lush, paddle-shaped green foliage, providing an attractive backdrop for the dazzling flowers.
', 4.20705298556734),
(158, 'Cannas (Canna)', 'Striking Canna lilies boast bold, tropical flair with large, paddle-shaped leaves in shades of green, bronze, or even variegated stripes. Their flamboyant flowers, often clustered atop tall stalks, come in a vibrant spectrum of colors including fiery reds, sunny yellows, warm oranges, delicate pinks, and creamy whites. The blooms feature asymmetrical petals and prominent stamen, adding to their exotic appeal. Cannas provide a long flowering period, typically blooming from summer through fall, bringing a burst of color to gardens and containers alike.
', 4.800423611789329),
(174, 'Cauliflower (Brassica oleracea var. botrytis Steady)', 'Cauliflower Steady doesnt produce a typical flower in the way we usually think of one. The edible curd is actually a mass of undeveloped flower buds, tightly packed together. The curd is typically a pristine, creamy white, though variations can occur. If left unharvested, these buds will eventually separate and develop into a loose, open flower head composed of small, bright yellow, four-petaled flowers, characteristic of the Brassica family. Flowering typically occurs in the plants second year, or if stressed, and is generally avoided in commercial production to maintain the desired curd quality. The flowering period is spring to early summer after the plant has overwintered.
', 2.010155980388625),
(181, 'Chalk Rose (Dudleya candida)', 'Chalk Rose (Dudleya candida) is a striking succulent characterized by its dense, chalk-white rosettes. These rosettes are composed of thick, fleshy leaves heavily coated in a powdery farina that protects the plant from intense sunlight. During the spring and summer months, it sends up flowering stalks adorned with clusters of small, creamy white to pale yellow, star-shaped flowers.
', 6.422089913249481),
(210, 'Common Fig (Ficus carica Violette de Bordeaux)', 'The Common Fig, particularly the Violette de Bordeaux cultivar, boasts an understated yet intriguing beauty. Its flowers, technically hidden within the developing fig fruit (syconium), are not visually prominent. The fruit itself, however, is highly ornamental. As it matures, the Violette de Bordeaux fig transforms from a green teardrop shape to a rounded form, eventually developing a striking deep violet to almost black skin. Inside, the pulp is a rich, deep red-purple, offering a sweet and intensely flavored reward. While the flowering period is internal and unseen, the fruit ripens typically from late summer into fall, providing a prolonged period of visual interest and delicious harvests.
', 9.57169527869332),
(214, 'Common Lilac (Syringa vulgaris Wonder Blue)', 'Wonder Blue Common Lilac: This cultivar showcases captivating, single flowers of a true blue hue, a rare and highly sought-after color in lilacs. The individual florets are small and densely packed into large, pyramidal panicles (flower clusters). Blooming in mid-spring, it perfumes the air with the classic, sweet, and intense lilac fragrance. The shrub itself is upright and multi-stemmed, with heart-shaped, dark green leaves that provide a lush backdrop for the vibrant blooms.
', 5.874246836464041),
(215, 'Common Milkweed (Asclepias syriaca)', 'The Common Milkweed (Asclepias syriaca) presents clusters of fragrant, dusty rose to pinkish-purple flowers, occasionally white. These flowers are uniquely structured with five reflexed petals and a central crown-like structure, known as the corona, composed of five upright horns. The blooms form large, spherical umbels, typically 2-6 inches in diameter. Flowering occurs from late spring to mid-summer (June-August).
', 5.7256477790003),
(226, 'Coppertone Stonecrop (Sedum nussbaumerianum Shooting Stars)', 'Coppertone Stonecrop Shooting Stars is a succulent prized for its striking color and texture. Its fleshy, lance-shaped leaves are a vibrant coppery-orange, intensifying to richer hues in full sun. The plant forms a low-growing, spreading rosette, creating a dense mat. In late winter to early spring, it produces clusters of star-shaped, bright yellow flowers that contrast beautifully with the foliage.
', 4.429228719237525),
(237, 'Coreopsis Lil Bang™ Darling Clementine', 'Coreopsis Lil Bang™ Darling Clementine is a delightful, compact perennial featuring semi-double to double flowers in a vibrant tangerine orange hue. The blooms, typically 1-2 inches in diameter, possess a charmingly ruffled appearance. Expect a profusion of flowers from early summer through fall, especially with regular deadheading. Its tidy, mounding habit reaches about 12 inches tall and wide, making it ideal for borders, containers, and mass plantings.
', 7.09201358901265),
(247, 'Crape Myrtle (Lagerstroemia indica Red Rocket®)', 'Striking, vibrant red blooms define the Red Rocket® Crape Myrtle. This deciduous tree explodes with masses of large, ruffled flower clusters from summer through fall, creating a long-lasting display of intense color. The individual flowers are delicate and crepe-paper-like, contributing to the overall showy effect. New foliage emerges bronze-red, maturing to a deep green before turning fiery red-orange in the fall. The smooth, exfoliating bark adds year-round interest, revealing a mottled pattern beneath.
', 5.418369891114632),
(248, 'Creeping Phlox (Phlox subulata Emerald Blue)', 'Creeping Phlox Emerald Blue is a captivating groundcover celebrated for its masses of star-shaped, vibrant blue flowers. These blossoms virtually blanket the plant in spring, typically from late spring to early summer, creating a stunning carpet of color. The foliage is needle-like and evergreen, providing year-round textural interest, even when not in bloom. The plants form is low-growing and spreading, making it ideal for rock gardens, slopes, or cascading over walls.
', 8.159187281460087),
(249, 'Creeping Phlox (Phlox subulata)', 'Creeping Phlox, or moss phlox, is a low-growing, mat-forming perennial prized for its vibrant spring display. Its needle-like, evergreen foliage creates a dense, moss-like carpet that becomes completely covered in small, five-petaled flowers. Blooms typically appear in April and May, creating a stunning blanket of color. Flowers come in a variety of shades, including pink, magenta, lavender, white, and occasionally blue. The overall effect is a colorful, textural groundcover that adds cheerfulness to rock gardens, slopes, and borders.
', 2.4358452454350203),
(255, 'Crepe Myrtle (Lagerstroemia Pink Velour®)', 'The Lagerstroemia Pink Velour®, or Pink Velour® Crepe Myrtle, is a captivating ornamental tree celebrated for its vibrant color and extended bloom time. It boasts masses of ruffled, crepe-paper-like flowers in a rich, velvety pink hue. The blooms are densely packed in panicles that cover the tree from summer through fall, typically July to September. Beyond the flowers, Pink Velour® offers year-round interest with its dark burgundy new foliage that matures to a deep green. In autumn, the leaves transform to shades of red and orange before falling, revealing a smooth, exfoliating bark mottled in shades of gray, brown, and tan. Its form is upright and vase-shaped, making it a striking addition to any landscape.
', 5.2753883685052605),
(269, 'Curly Parsley (Petroselinum crispum var. crispum)', 'Curly Parsley (Petroselinum crispum var. crispum) boasts vibrant, emerald-green, tightly curled leaves that form a dense, compact mound. Its primarily grown for its foliage, as the edible leaves are its defining characteristic. Flowering, when it occurs, produces umbels of tiny, greenish-yellow flowers on tall stalks in its second year, typically during the summer months. The flowers are relatively insignificant compared to the plants lush, ruffled foliage.
', 7.944806236003535),
(273, 'Dahlia Creme de Cassis', 'Dahlia Creme de Cassis is a captivating decorative dahlia distinguished by its unique coloration. The petals are a blend of creamy white and deep, wine-purple hues, creating a striking contrast. The color deepens towards the base of the petals, resembling the liqueur its named after. The large, fully double blooms exhibit a classic dahlia form, with petals that are slightly twisted and recurved, giving the flower a full and elegant appearance. Creme de Cassis typically flowers from mid-summer through the first frost, providing a long-lasting display in the garden.
', 5.250152863482711),
(288, 'Daylily (Hemerocallis Put My Picture on the Cover)', 'Hemerocallis Put My Picture on the Cover is a striking daylily boasting large, ruffled blooms with a vibrant color palette. The petals are a blend of deep rose-pink, transitioning to a lighter, more luminous pink towards the edges. A prominent, contrasting yellow-gold throat radiates outwards, accentuating the flowers center. The form is characterized by its substantial size, recurved petals with heavily ruffled edges, and robust, slightly fragrant blooms. Expect flowering to occur in mid-season, providing a burst of color and drama to the garden during this period.
', 2.1809566385841306),
(303, 'Dianthus (Dianthus monspessulanus)', 'Dianthus monspessulanus, also known as the Fringed Pink, presents delicate, often solitary flowers atop slender stems. The petals are a soft pink to lilac hue, deeply fringed or lacerated at the edges, giving them a lacy appearance. Its form is graceful and somewhat airy. Flowering typically occurs in late spring to early summer, gracing meadows and rocky slopes with its understated beauty.
', 4.238059040229579),
(304, 'Dill (Anethum graveolens Bouquet)', 'The Bouquet Dill flower presents a delicate, lacy umbel of vibrant yellow-green florets. Its form is characterized by multiple flat-topped clusters of tiny flowers arranged in a complex, almost cloud-like structure. Flowering typically occurs in mid-summer, attracting beneficial insects to the garden.
', 3.8550011137264937),
(310, 'Double Japanese Wisteria (Wisteria floribunda Black Dragon)', 'Wisteria floribunda Black Dragon (also known as Kokuryu) is a stunning double Japanese wisteria celebrated for its intensely fragrant, long, and densely packed flower clusters. The blossoms are a rich, deep violet-purple, often described as a near-black hue in bud before opening to reveal their full color. The flowers are uniquely double, giving them a fuller, more robust appearance than single-flowered varieties. These dramatic racemes can reach lengths of up to 1-2 feet. Black Dragon typically blooms in mid to late spring, creating a spectacular cascade of color and fragrance.
', 3.711003759896615),
(322, 'Dwarf Chinese Astilbe (Astilbe rubra Pumila)', 'Dwarf Chinese Astilbe Pumila is a charming, low-growing perennial celebrated for its fluffy, vibrant rose-red flower plumes. Its blooms rise just above a compact mound of fern-like, deeply divided foliage, creating a textural and colorful display. Typically flowering in mid-summer, its rosy-red spires provide a burst of color and airy elegance to the garden.
', 1.7363357702964208),
(323, 'Dwarf Coneflower (Echinacea Kismet® Red)', 'Echinacea Kismet® Red is a vibrant, compact coneflower showcasing masses of intense, true-red daisy-like flowers. Each bloom features prominent, golden-orange central cones surrounded by slightly reflexed petals. This long-blooming perennial offers continuous color from early summer through fall. Its sturdy, well-branched habit makes it ideal for borders, containers, or mass plantings.
', 5.374441588492612),
(324, 'Dwarf Mouse-ear Tickseed (Coreopsis auriculata Nana)', 'Dwarf Mouse-ear Tickseed Nana is a charming, compact perennial boasting cheerful, daisy-like flowers. Its blooms are a sunny golden-yellow with a darker, often orange-yellow, center disk. The plant forms a low, dense mound of fuzzy, rounded, mouse-ear-like foliage. Flowering typically occurs from late spring to mid-summer, often with sporadic rebloom throughout the season if deadheaded. Reaching only 6-12 inches tall and spreading 12-18 inches wide, its an excellent choice for edging, rock gardens, or the front of borders.
', 5.7563206456843234),
(335, 'Echeveria Blue Wren', 'Echeveria Blue Wren is a captivating succulent featuring rosettes of thick, fleshy leaves with a powdery blue-gray coloration, often tinged with pink or purple highlights, especially along the margins and tips. The rosette form is generally compact and symmetrical. When mature, it produces tall, arching flower spikes bearing bell-shaped flowers that are typically coral-pink to orange-red, blooming primarily in the spring and summer months.
', 4.6790248211036864),
(339, 'Echeveria Rain Drops', 'Echeveria Rain Drops is a captivating succulent prized for its unique appearance. Its fleshy, rounded leaves are a cool, powdery blue-green color, often tinged with pink or purple at the edges when stressed by sunlight or cooler temperatures. The most distinctive feature is the raised, blister-like caruncle on the upper surface of each leaf, resembling a single, perfect raindrop. These raindrops add a fascinating texture and visual interest to the plant. During its blooming period, typically in spring or summer, it sends up tall flower stalks adorned with bell-shaped, coral-pink to orange flowers.
', 9.97547343047367),
(370, 'Fancy-Leafed Caladium (Caladium bicolor)', 'The Fancy-Leafed Caladium (Caladium bicolor) is celebrated for its vibrant and diverse foliage. Its large, arrow-shaped or heart-shaped leaves showcase striking combinations of colors, including shades of red, pink, white, green, and copper. Patterns range from bold veins and blotches to speckled or mottled appearances. While Caladiums do produce flowers – inconspicuous spadices surrounded by spathes – they are typically removed to encourage more vibrant foliage growth. They are primarily grown for their showy leaves, which emerge from tubers and provide a tropical flair. With proper care, the foliage can last throughout the warm growing season.
', 7.369817840817603),
(382, 'Flowering Pear (Pyrus calleryana Cleveland Select)', 'The Cleveland Select Flowering Pear is a graceful, upright tree known for its profuse, fragrant, white blossoms in spring. It boasts a symmetrical, pyramidal to oval form. The flowers are small, typically about an inch in diameter, and densely clustered, completely covering the branches in early to mid-spring before the leaves emerge. The flowering period lasts for approximately two weeks. In fall, the foliage transforms to brilliant shades of red, orange, and purple.
', 4.184896903297563),
(386, 'Foxglove (Digitalis Honey Trumpet)', 'Honey Trumpet Foxglove (Digitalis) presents elegant spires adorned with unique, downward-facing, trumpet-shaped flowers. The blossoms showcase a warm, honey-apricot hue, often displaying delicate maroon speckles within their throats. These stately plants typically bloom in early to mid-summer, providing a vertical accent and attracting pollinators like bees and hummingbirds to the garden. Their lance-shaped foliage forms a basal rosette from which the flower stalks emerge, creating a striking silhouette.
', 3.156476544700482),
(404, 'Garden Sage (Salvia officinalis Robert Grimm)', 'Robert Grimm Garden Sage offers a delightful display of color and texture. It features vibrant, two-toned flowers with a deep violet-blue upper lip and a lighter, almost lilac-blue lower lip. The blooms are densely packed on upright spikes that rise above the plants grey-green, textured foliage. Flowering occurs primarily in late spring to early summer, with potential for repeat blooms throughout the season if deadheaded. The plant maintains a compact, bushy form, making it an attractive and manageable addition to the garden.
', 5.69332136866378),
(410, 'Garlic (Allium sativum Early Red Italian)', 'Garlic flowers (Allium sativum Early Red Italian) are not typically grown for their ornamental value, as they are primarily cultivated for their flavorful bulbs. However, when allowed to flower, they produce a globe-shaped umbel atop a tall, sturdy stalk. The umbel is composed of numerous small, star-shaped flowers that are typically a pale pinkish-purple to white. Flowering typically occurs in late spring to early summer.
', 8.05332340049004),
(419, 'Geranium (Geranium wallichianum Crystal Lake)', 'Geranium Crystal Lake is a stunning perennial boasting saucer-shaped flowers of the palest lavender-blue, almost white, with intricate veining in deeper violet and a striking white eye. The flowers, typically 1-1.5 inches across, are borne in profusion above mounds of deeply divided, mid-green foliage. Flowering is generous and long, typically starting in late spring and continuing throughout the summer, and often into early autumn with deadheading. The plant maintains a relatively low, spreading habit, typically reaching 12-18 inches in height and spreading up to 24 inches wide.
', 9.710147323993704),
(423, 'Gladiola (Gladiolus)', 'Stately gladiolus, often called sword lilies, command attention with their tall, erect flower spikes. Their blossoms, available in a dazzling array of colors from pure white and soft pastels like pink and lavender to vibrant reds, oranges, yellows, and even bi-colors, are formed of trumpet-shaped florets that bloom sequentially from the bottom up. These elegant flowers typically appear in mid-summer, providing a long-lasting display that can extend into early autumn. The sword-like leaves provide a strong vertical accent, complementing the dramatic floral display.
', 5.376215800406026),
(429, 'Golden Sage (Salvia officinalis Aurea)', 'Golden Sage (Salvia officinalis Aurea) is a striking perennial herb prized for its ornamental foliage. Its leaves are ovate and textured, displaying a beautiful variegation of green and gold, with the golden hues being most prominent in bright sunlight. The plant forms a bushy, rounded shape, typically reaching 1-2 feet in height and spread. While primarily grown for its foliage, Golden Sage produces spikes of lavender-blue flowers in late spring to early summer, attracting pollinators.
', 6.232190788184898),
(430, 'Gooseberry (Ribes uva-crispa Hinnonmaki Rod)', 'The Gooseberry Hinnonmaki Rod boasts small, bell-shaped flowers, typically a greenish-yellow hue, sometimes tinged with red. These unassuming blooms dangle delicately from the thorny branches in early spring, usually around April or May.
', 6.149375146868174),
(431, 'Gooseberry (Ribes uva-crispa)', 'The Gooseberry flower is a subtle beauty, often overlooked amongst the spiny branches of its host plant. Individually small and bell-shaped, they hang delicately from the leaf nodes in clusters of one to three. The flowers are typically a greenish-white or pale greenish-yellow, sometimes tinged with pink or purple. Their form is unassuming, with recurved sepals that flare outwards, revealing the delicate petals within. Flowering occurs in spring, usually April to May, coinciding with the emergence of new leaves.
', 0.3109059575605516),
(441, 'Hardy Geranium (Geranium sanguineum var. striatum)', 'Delicate and charming, *Geranium sanguineum var. striatum*, often called Striated Bloody Cranesbill, offers a profusion of pale pink, cup-shaped flowers delicately etched with darker pink veins. Each five-petaled blossom is small and understated, creating a beautifully textured effect en masse. This low-growing perennial forms a neat, mounded habit of deeply divided, dark green foliage that can turn reddish-bronze in autumn. It boasts a long flowering period, typically blooming from late spring through summer, offering continuous color and attracting pollinators.
', 3.22366120102413),
(444, 'Hardy Hibiscus (Hibiscus moscheutos Tie Dye)', 'Hardy Hibiscus Tie Dye is a captivating perennial known for its enormous, dinner-plate sized blooms. The flowers feature a stunning tie-dye effect with swirling patterns of deep burgundy-red, rosy pink, and creamy white, creating a unique and mesmerizing display on each bloom. The petals are slightly ruffled and surround a prominent central column. Tie Dye blooms profusely throughout the summer, typically from mid-summer to early fall, attracting hummingbirds and butterflies. The plant has a bushy, upright habit with attractive, dark green foliage that provides a lush backdrop for the vibrant flowers.
', 5.441963491004972),
(447, 'Hardy Hibiscus Hybrid (Hibiscus Summer in Paradise)', 'Hibiscus Summer in Paradise is a tropical-looking hardy hibiscus boasting enormous, dinner-plate-sized flowers. These blooms are a captivating blend of bright coral-red and deep crimson, often featuring a prominent dark red eye in the center. The petals have a slightly ruffled or crinkled texture, adding to their visual appeal. This hibiscus exhibits a shrub-like form with a dense, bushy habit and attractive, dark green foliage. Summer in Paradise blooms profusely from midsummer to early fall, providing a long season of vibrant color.
', 7.231511418779295),
(451, 'Hen and chicks (Sempervivum Dea)', 'Sempervivum Dea, commonly known as Hen and Chicks, is a captivating succulent prized for its striking coloration and unique growth habit. The hen (mother plant) produces numerous chicks (offsets) clustered around it, creating a visually appealing rosette formation. Dea exhibits vibrant foliage, often displaying shades of deep red, burgundy, and bronze, sometimes with green undertones depending on the season and sun exposure. The pointed leaves are fleshy and form tightly packed rosettes typically ranging from 2 to 4 inches in diameter. While primarily grown for its foliage, Dea may occasionally produce tall, sturdy flower stalks in the summer bearing clusters of small, star-shaped pink to reddish-purple flowers.
', 2.4085409211055246),
(458, 'Hen and Chicks (Sempervivum tectorum Grammens)', 'Sempervivum tectorum Grammens, commonly known as Hen and Chicks, showcases captivating rosettes of succulent leaves. The fleshy leaves are a striking blend of colors, ranging from vibrant green to deep burgundy-red, often with contrasting tips. The rosettes form a tight, spherical shape, with the larger hen plant surrounded by numerous smaller chick offsets. Mature plants, typically after several years, produce stout stalks adorned with clusters of star-shaped, pink to reddish-purple flowers in the summer months.
', 0.6275268491800342),
(481, 'Hummingbird Sage (Salvia coccinea Coral Nymph)', 'Hummingbird Sage Coral Nymph is a captivating perennial featuring bicolor blooms in a delicate coral and white. The upper petals present a soft coral hue, contrasting beautifully with the crisp white lower lip. Flowers are arranged in loose, airy spikes held above ovate, mid-green foliage. Blooming profusely from spring through fall, Coral Nymph provides a long season of color and attracts hummingbirds with its nectar-rich blossoms. Its upright, bushy form reaches 1-2 feet in height and width.
', 3.4226913219946447),
(482, 'Hyacinth (Hyacinthus orientalis Blue Jacket)', 'Blue Jacket Hyacinth is a striking cultivar known for its dense, cylindrical flower spikes densely packed with intensely fragrant, bell-shaped florets. The color is a rich, deep indigo blue, often with a contrasting white edge to each petal, giving it a distinctive, almost bi-color appearance. It blooms in mid-spring, typically in April, adding a burst of vibrant color and powerful fragrance to the garden. The flower spikes are held upright on sturdy stems, rising above a rosette of lance-shaped, glossy green leaves.
', 0.9749099972506232),
(484, 'Hyacinths (Hyacinthus)', 'Fragrant and showy Hyacinths boast dense spikes of bell-shaped flowers in a vibrant range of colors, including blues, purples, pinks, whites, yellows, and reds. Their waxy petals curl back slightly at the tips. These spring-blooming bulbs produce thick, strap-like foliage and typically flower from mid to late spring, filling gardens with their sweet, intense fragrance.
', 5.326644982566453),
(492, 'Iceland Poppy (Papaver nudicaule Champagne Bubbles White)', 'Delicate and ethereal, Iceland Poppy Champagne Bubbles White showcases pristine, papery-thin petals in a luminous, pure white. Its cup-shaped blooms, often slightly ruffled, dance atop slender, wiry stems, creating a graceful and airy appearance. Blooming primarily from spring to early summer, and often with repeat flushes in cooler climates, this poppy adds a touch of understated elegance to any garden.
', 2.5406553207915374),
(496, 'Itoh Peony (Paeonia Caroline Constabel)', 'Caroline Constabel Itoh Peony: A captivating semi-double Itoh peony displaying vibrant, coral-red blooms. The flowers are large, often reaching 8-10 inches in diameter, with petals subtly fading to lighter shades at the edges. Its robust, bushy foliage remains attractive throughout the growing season, resembling that of a herbaceous peony. Blooming begins in late spring to early summer, often extending the peony season with a longer flowering period than traditional varieties. Strong stems support the impressive blooms, minimizing the need for staking.
', 9.74267478260921),
(500, 'Japanese Honeysuckle (Lonicera japonica Halliana)', 'Japanese Honeysuckle Halliana is a twining vine celebrated for its fragrant and abundant blooms. Its flowers open pure white, gradually aging to a rich, creamy yellow, creating a two-toned effect on the plant. The blossoms are tubular, with deeply divided, reflexed lips, typical of honeysuckle flowers. It boasts a long flowering period, typically from late spring through summer and often into early fall, filling the air with a sweet, intoxicating scent, especially in the evening.
', 6.8885680296899645),
(511, 'Judd Viburnum (Viburnum carlesii var. bitchiuense)', 'Judd Viburnum: A captivating shrub celebrated for its intensely fragrant, snowball-like flower clusters. These start as rosy-pink buds, unfurling into rounded, 2-3 inch diameter blooms of pristine white. Blooming in mid-spring, the fragrance permeates the air, reminiscent of spicy cloves. The shrub itself is rounded and compact, with attractive, dark green foliage that provides a lovely backdrop for the blossoms. In fall, the leaves may turn reddish-purple, adding further seasonal interest.
', 4.48682910331988),
(513, 'Jujubes (Ziziphus jujuba)', 'The jujube flower is a small, inconspicuous bloom, typically creamy white to pale yellow-green. Its form is star-shaped, with five delicate, recurved petals surrounding a central cluster of stamens. Flowering occurs relatively late in the season, typically in late spring to early summer, providing a subtle but important source of nectar for pollinators.
', 1.2131564863178252),
(519, 'Lambs Ears (Stachys)', 'Lambs Ears (Stachys byzantina) is adored for its soft, velvety, silver-gray leaves that resemble, unsurprisingly, a lambs ear. The foliage forms a dense, low-growing mat, creating a lovely textural ground cover. While primarily grown for its foliage, it does produce upright flower spikes during the summer months. These spikes bear small, insignificant flowers that are typically pinkish-purple to lavender. Although the flowers are not the main attraction, they add a touch of vertical interest and attract pollinators.
', 4.9016018447237695),
(523, 'Larkspur (Delphinium Benarys Pacific Cameliard)', 'Benarys Pacific Cameliard Larkspur boasts towering spires of semi-double to double flowers in a captivating mix of lavender and violet shades, often exhibiting a subtle gradient of color within each bloom. The individual flowers are densely packed along the upright stems, creating a full and impressive display. Blooming typically occurs from early summer to mid-summer, offering a vertical accent to the garden. The plant features deeply lobed, fern-like foliage that remains attractive throughout the growing season.
', 7.677184792160069),
(524, 'Larkspur (Delphinium elatum Guardian Lavender)', 'Guardian Lavender Larkspur presents spires of semi-double, lavender-purple flowers with a contrasting white bee in the center. These tall, elegant flower spikes rise above a compact mound of deeply divided, green foliage. Blooming typically occurs from early to mid-summer, often with a second flush of flowers if spent blooms are promptly removed. It is prized for its upright, stately form and its ability to attract pollinators to the garden.
', 2.923680850264432),
(527, 'Leek (Allium ampeloprasum Large American Flag)', 'Leek flowers, when allowed to bloom, emerge as a large, globe-shaped umbel atop a tall, sturdy stalk. The umbel is composed of many tiny, star-shaped flowers that are typically a shade of pale purple or lavender, sometimes tending towards white. Flowering usually occurs in the second year of growth, typically in mid to late summer.
', 2.5418521791690822),
(528, 'Leek (Allium ampeloprasum Zermatt)', 'Globular flowerheads composed of densely packed, star-shaped florets. Typically a soft lilac-purple, occasionally fading to a near-white at the tips. Forms a striking spherical umbel atop a tall, sturdy stem. Blooms in mid-summer, offering a long-lasting display.
', 9.06621994468194),
(545, 'Lily (Lilium Corsage)', 'Lilium Corsage is an elegant Asiatic lily known for its upward-facing, bowl-shaped flowers. Its petals display a delicate blend of creamy white flushed with soft pink, often deepening towards the center. The blooms are typically 4-6 inches across and appear atop strong, upright stems. Corsage lilies bloom in mid-summer, adding a touch of sophistication and gentle color to gardens and floral arrangements.
', 7.2664651182782),
(546, 'Lily (Lilium Flavia)', 'Lilium Flavia is a striking Asiatic lily known for its vibrant, upward-facing blooms. The flowers feature a bold, rich tangerine orange color, often with a subtle speckling of darker orange or brown towards the center. Each flower boasts a classic lily form with six gently recurved petals, creating an open, star-like shape. Flavia typically flowers in mid-summer, offering a burst of warm color when many other flowers are fading. It exhibits strong, upright stems and healthy green foliage.
', 5.317622189142568),
(553, 'Lily (Lilium pyrenaicum)', 'The Lilium pyrenaicum, or Pyrenean Lily, is a striking flower with nodding, bell-shaped blooms. Its petals are typically a vibrant yellow, heavily speckled with dark purple or brown spots, giving it a distinctive appearance. The flowers are arranged in a raceme, with multiple blossoms per stem. It blooms in early summer, releasing a strong, somewhat pungent fragrance. The plant itself features narrow, lance-shaped leaves along a tall, slender stem.
', 4.469094414546937),
(566, 'Mexican Butterwort; Mexican Ping (Pinguicula ibarrae)', 'The Mexican Butterwort, *Pinguicula ibarrae*, is a captivating carnivorous rosette, typically 2-4 inches in diameter. Its leaves are succulent, light green to reddish-purple depending on light exposure, and covered in glistening droplets of mucilage that attract and trap small insects. From late spring to fall, it produces delicate, spurred flowers on slender stalks. The petals are typically a beautiful violet-purple with a contrasting white or pale yellow throat, though color variations can occur. The flower form is somewhat irregular, with a distinct lower lip.
', 0.8651007339261136),
(571, 'Miniature Jonquilla Daffodil (Narcissus Pipit)', 'Pipit is a charming miniature jonquilla daffodil boasting multiple fragrant, creamy-yellow flowers per stem. Each bloom features a slightly darker, golden-yellow cup surrounded by delicate, reflexed petals of a paler, buttery hue. Blooming in mid-spring, Pipit forms a compact clump of slender, blue-green foliage, making it ideal for rock gardens, borders, or containers. Its prolific flowering and delightful fragrance make it a welcome addition to any spring garden.
', 6.608659752793333),
(576, 'Morning Glory (Ipomoea Split Second)', 'Split Second Morning Glory boasts a captivating display of bi-colored blooms. Its petals are a rich, velvety purple-blue, dramatically edged with a crisp, pure white border. The trumpet-shaped flowers unfurl each morning, revealing a star-shaped center, and typically last for a single day. This variety is known for its vigorous climbing habit and abundant flowering, providing a profusion of color throughout the summer and into early fall.
', 2.0332805823232305),
(584, 'Nepeta (Nepeta subsessilis)', 'Upright Japanese catmint, *Nepeta subsessilis*, offers a robust and refined presence. Its flowers, typically a rich lavender-blue to violet, are densely packed into tiered whorls along upright stems. These stems are adorned with coarsely toothed, heart-shaped green leaves. Blooming from mid-summer to early fall, it provides a long-lasting display of color and attracts pollinators in droves. Its form is more upright and less sprawling than many other catmints.
', 2.580752230700312),
(615, 'Pacific Coast Iris (Iris Caught in the Wind)', 'Caught in the Wind Pacific Coast Iris is a captivating beauty, showcasing a blend of creamy white standards and falls delicately veined with lavender-blue. Its elegant form features slightly ruffled petals, providing a soft, airy appearance, reminiscent of its namesake. Blooming in the spring, typically from April to May, this iris brings a touch of refined charm to woodland gardens or shaded borders.
', 2.080860608292932),
(650, 'Pineberry (Fragaria x ananassa White Carolina)', 'The Pineberry (Fragaria x ananassa White Carolina) is a unique strawberry cultivar. Its berries are small to medium in size, typically round to conical, and characterized by a striking white to pale pink color when ripe. The defining feature is the presence of red seeds (achenes) dotting the surface. Its flowering period is similar to that of standard strawberries, generally in spring, producing small, white, five-petaled flowers typical of the strawberry family.
', 9.167587924317239),
(696, 'Rape (Brassica napus subsp. napus)', 'Bright, sunny yellow cruciform flowers in dense, terminal racemes characterize rape (Brassica napus subsp. napus). Each flower possesses four petals arranged in a cross shape, typical of the Brassicaceae family. Flowering occurs primarily in spring, creating vast fields of vibrant yellow landscapes. The plant exhibits robust green foliage and can grow to significant heights, providing a striking visual impact during its bloom.
', 5.853339348369542),
(700, 'Red Flowering Currant (Ribes sanguineum Brocklebankii)', 'Brocklebankii Red Flowering Currant is a deciduous shrub prized for its vibrant spring display. It boasts clusters of deep rose-red to crimson flowers that dangle gracefully from bare branches in early to mid-spring. The shrub itself features rounded, golden-yellow foliage that matures to chartreuse-green as the season progresses, providing a colorful backdrop even after the blooms fade. Its form is typically upright and bushy, reaching a mature height and spread of around 4-6 feet. The flowers are followed by dark blue berries, though these are less ornamental.
', 7.82458241176031),
(721, 'Rose (Rosa Lavender Crush)', 'Lavender Crush Rose: A captivating floribunda rose showcasing clusters of uniquely colored blooms. The flowers exhibit a captivating lavender hue with subtle hints of pink and mauve, creating a soft, romantic effect. The blooms are medium-sized, double, and possess a classic, cupped form. This rose boasts a strong, sweet fragrance. Lavender Crush offers repeat blooms throughout the season, from late spring until frost, providing a continuous display of color.
', 0.13390181298055215),
(724, 'Rose (Rosa The Pilgrim)', 'The Pilgrim is a beautiful English Rose known for its soft, buttery-yellow blooms. The flowers are large, cupped and quartered, packed with numerous petals that create a rich, full form. It is a repeat-flowering rose, offering a generous display throughout the summer and into the autumn. The fragrance is strong and pleasing, a delightful blend of tea rose and myrrh.
', 5.803092817719006),
(727, 'Rose of Sharon (Hibiscus Pollypetite™)', 'The Hibiscus Pollypetite™ Rose of Sharon is a compact, shrubby cultivar offering a profusion of semi-double, vibrant blooms. Typically, the flowers display a captivating mix of shades, often featuring lavender, pink, or white petals with a contrasting deep red or purple eye. Its rounded form and diminutive size make it ideal for smaller gardens or container planting. This variety is known for its extended flowering period, typically blooming from mid-summer through fall, providing long-lasting color and attracting pollinators.
', 9.036454564086808),
(731, 'Roses (Rosa)', 'Classic and beloved Roses (Rosa) exhibit a vast array of colors, from pristine whites and soft pastels to vibrant yellows, oranges, deep reds, and even purples. Their form is equally diverse, ranging from the classic, high-centered blooms of hybrid teas to the clustered sprays of floribundas and the delicate, single blooms of wild roses. Petals can be velvety smooth or subtly textured, and their arrangement varies from tightly coiled to loosely unfurled. Flowering period depends greatly on the variety, but many roses bloom repeatedly throughout the growing season, from late spring or early summer until the first frost.
', 6.191061189823481),
(736, 'Saffron Crocus (Crocus sativus)', 'The Saffron Crocus is a small, enchanting flower boasting delicate lavender to lilac petals. Its goblet-shaped blooms are relatively short-lived, rising directly from the soil without a stem. The defining characteristic is its vibrant crimson stigmas, the source of saffron spice, which dramatically contrast with the paler petals. It flowers in the autumn, typically in October and November, providing a splash of color as other plants begin to fade.
', 7.038690065080716),
(750, 'Shasta Daisies (Leucanthemum x superbum)', 'The Shasta Daisy is a classic and cheerful flower featuring a bright white ray florets surrounding a golden-yellow central disc. These single or double petaled rays are typically arranged in a simple, elegant form around the prominent center. Shasta Daisies typically bloom profusely from late spring through late summer, providing a long season of daisy-like charm to gardens and bouquets. Their sturdy stems and upright growth habit make them ideal for cutting.
', 8.157894919460892),
(772, 'Softneck Garlic (Allium sativum Inchelium Red)', 'Inchelium Red is a robust softneck garlic known for its beautiful appearance and flavorful cloves. Its bulbs boast a creamy white skin often streaked with purple or red blushing. The cloves are crescent-shaped, plump, and wrapped in colorful wrappers ranging from deep red to shades of rose and tan. While it rarely flowers, if it does, the scape produces a bulbiferous head with small, pinkish-white bulbils.
', 1.4311342252338304),
(774, 'Speedwell (Veronica oltensis)', 'Oltensis Speedwell (Veronica oltensis) displays a charming show of bright blue, sometimes violet-blue, flowers. These tiny, four-petaled blossoms are densely packed along upright, slender spikes, creating a vibrant and eye-catching display. It typically flowers in late spring to early summer, offering a burst of color when many other spring blooms are fading. The plant itself is a relatively low-growing perennial, often forming a spreading clump.
', 8.36022869728748),
(776, 'Spider Plant (Chlorophytum comosum)', 'Delicate and star-like, Spider Plant flowers are typically small and white. They appear on long, wiry stems (up to 2-3 feet long) that arch away from the mother plant. The individual flowers are usually only about half an inch in diameter, with six slender petals. Flowering is sporadic and not guaranteed, but most commonly occurs during the warmer months, especially spring and summer, when the plant is mature and receiving adequate light.
', 3.179821436026054),
(777, 'Spike Speedwell (Veronica spicata Royal Candles)', 'Spike Speedwell Royal Candles is a charming perennial boasting dense, upright spikes of rich, royal purple flowers. The individual flowers are small and tubular, tightly packed along the spike. The foliage is comprised of lance-shaped, dark green leaves forming a neat, basal clump. Blooming from early to mid-summer, it provides a long-lasting display of vibrant color.
', 5.625057962208533),
(801, 'Sunroot (Helianthus tuberosus White Fuseau)', 'The White Fuseau Sunroot (Helianthus tuberosus) offers a profusion of creamy white, daisy-like flowers with a golden-yellow central disc. These blooms are typically 2-3 inches wide and are borne atop tall, sturdy stems. Its form is upright and branching, producing an abundance of foliage and flowers. Flowering occurs in late summer to autumn, generally from August to October, providing a late-season nectar source for pollinators.
', 4.585789582174262),
(815, 'Swiss Chard (Beta vulgaris subsp. cicla Bright Lights)', 'While Bright Lights Swiss chard is primarily grown for its vibrant, multi-colored stems and leaves, its flowers are less showy. When it bolts (goes to seed), it produces tall, branching flower spikes. The flowers themselves are small, greenish-white and inconspicuous. They are densely packed along the spikes. Flowering typically occurs in the second year of growth or after exposure to cold temperatures, usually in late summer or fall.
', 5.924354038846973),
(816, 'Swiss Chard (Beta vulgaris subsp. cicla Rhubarb Chard)', 'Rhubarb Chard, when allowed to bolt, produces a tall, branching flower stalk reaching several feet in height. The individual flowers are small and inconspicuous, typically greenish-white, and clustered densely along the stalk. Flowering usually occurs in the plants second year, typically in the summer months. The overall form is reminiscent of other Beta vulgaris species, with a somewhat weedy appearance, sacrificing the vibrant leaf color for seed production.
', 9.700762816643294),
(822, 'Tall Bearded Iris (Iris Serene Silence)', 'Serene Silence Tall Bearded Iris: This iris exudes quiet elegance with its pristine white standards (upright petals) and falls (drooping petals). A delicate, pale lemon-yellow beard provides a subtle contrast and warmth. The form is classic and ruffled, with elegantly arched falls. Expect blooms in mid-season, typically late spring to early summer. Its stately stalks reach heights of 36-40 inches, making it a striking addition to any garden.
', 0.828391007387122),
(823, 'Tall Bearded Iris (Iris Wonders Never Cease)', 'Wonders Never Cease Tall Bearded Iris is a captivating beauty boasting heavily ruffled standards of warm, peachy-pink, complementing its deeply saturated violet-purple falls. A vibrant tangerine beard adds a fiery contrast. The large, showy blooms are held on tall, sturdy stalks, reaching heights of 36-40 inches. Expect a mid-season bloom period, typically in late spring to early summer. Its form is elegant and classic, with a strong, upright presence.
', 1.3821778322951166),
(850, 'Triandrus Daffodil (Narcissus Thalia)', 'Narcissus Thalia, commonly known as Triandrus Daffodil Thalia, is an elegant and fragrant daffodil. It boasts pure white, nodding flowers, typically with two to three blooms per stem. Each flower features gracefully reflexed petals surrounding a small, delicate cup. Thalia blooms in mid-spring, offering a refreshing and bright display. Its foliage is a cool green, adding to its overall delicate appearance.
', 5.77849601093024),
(866, 'Van Houtte Spiraea (Spiraea x vanhouttei Pink Ice)', 'Pink Ice Van Houtte Spiraea: This deciduous shrub offers a delightful twist on the classic Van Houtte Spiraea with its variegated foliage. The leaves are splashed with shades of pink, cream, and green, providing multi-seasonal interest even when not in bloom. In late spring to early summer, it produces abundant clusters of small, white flowers that contrast beautifully against the colorful foliage. The shrub has a graceful, arching habit, typically reaching 5-8 feet in height and width.
', 0.4571082966059704),
(868, 'Variegated Queen Victoria Century Plant (Agave victoriae-reginae Albomarginata)', 'The Variegated Queen Victoria Century Plant, *Agave victoriae-reginae* Albomarginata, is a striking succulent prized for its architectural form and crisp variegation. It forms a tight, almost spherical rosette of thick, triangular leaves, typically 6-12 inches in diameter. The leaves are dark green, almost black-green in strong light, and are edged with a clean, bright white or creamy-white margin. These margins accentuate the leafs shape and create a beautiful contrast. The edges of the leaves are smooth, lacking teeth or spines, except for a sharp, dark terminal spine.

Like the species, it is monocarpic, meaning it flowers only once in its lifetime. This flowering event, which can take decades to occur (hence the name Century Plant, though it doesnt actually take a century!), results in a massive flower stalk that can reach up to 15 feet tall. The stalk bears numerous greenish-yellow flowers. After flowering, the mother plant dies, but offsets (pups) often form around the base, continuing the plants lineage. The flowering period is highly variable and depends on the plants age, environmental conditions, and location.
', 0.2917772986034104),
(892, 'Winter Radish (Raphanus sativus China Rose)', 'Winter Radish China Rose produces delicate, four-petaled flowers in shades of pale pink to lavender. These small, cruciform blossoms emerge in spring, after the plant has overwintered, atop tall, branching stems. The flowers are followed by seed pods, which are also edible when young. While grown primarily for its root, the flowering period adds an unexpected, ornamental touch to the late spring garden.
', 0.11603871481687925),
(901, 'Yarrow (Achillea Moonshine)', 'Achillea Moonshine is a striking yarrow prized for its long bloom time and silvery-green foliage. It showcases clusters of bright, lemon-yellow flowers in a flattened, disc-like form atop sturdy stems. Blooming profusely from early summer to early fall, it offers long-lasting color. The finely-divided, fern-like foliage adds textural interest to the garden even when not in bloom.
', 9.40956404797293),
(905, 'Yarrow (Achillea millefolium Summer Pastels)', 'Summer Pastels Yarrow offers a delightful mix of soft, muted colors in shades of cream, yellow, pink, rose, and apricot. Its flowers are tiny and densely packed into flat-topped clusters, creating a wildflower-like effect. Blooming from early summer through fall, it features fern-like, aromatic foliage that provides an attractive backdrop to the long-lasting blooms.
', 3.093285527356533);
